# Site
name: 'Rodzinne Strony'
description: 'Oto strona o tym co ważne - dla dużych i małych. O różnych spojrzeniach na to samo, bo oczy patrzące są rózne.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/RodzinneStrony'
disqus: ''
email: ''
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Klara:
      name:           Klara       
      avatar:         /assets/images/tina1.jpg
      bio:            "Mam 8 lat. Lubię kotki i cukier."
    

    Paulina:
      name:           Paulina
      avatar:         /assets/images/avatar2.jpg
      bio:            "Mama dwójki - na dobre i złe. Razem patrzymy, rozmawiamy, wymyślamy."
      
    Eryk:
      name:           Eryk       
      avatar:         /assets/images/avatar1.jpg
      bio:            "Mam 2,5 roku. Biegam, krzyczę, mówię non stop i mam pełną głowę pomysłów i loczków."
      
    Łukasz:
      name:           Łukasz    
      avatar:         /assets/images/avatar1.jpg
      bio:            ""
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
